CREATE TABLE users (id VARCHAR(36) NOT NULL, name TEXT NOT NULL, hoby TEXT NOT NULL, PRIMARY KEY (id));
CREATE TABLE posts (id VARCHAR(36) NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, created TEXT NOT NULL, author_id VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY (author_id) REFERENCES users(id));
